/**
 * @fileoverview `BlockId` value object: the stable identifier of a content
 * block within a landing page.
 */

import { Result } from '../../../../shared/core/result/result';

/**
 * Value object wrapping a non-empty block identifier.
 *
 * The id is opaque to the domain; it is generated by the backend on
 * creation. New, not-yet-persisted blocks can use {@link BlockId.generate}
 * to obtain a temporary client-side id.
 */
export class BlockId {
  /**
   * @param value - The validated identifier string.
   */
  private constructor(public readonly value: string) {}

  /**
   * Rehydrates a {@link BlockId} from an existing identifier (e.g. one
   * received from the API).
   *
   * @param raw - The identifier string.
   * @returns A successful result, or a failure when the id is empty.
   */
  public static create(raw: string): Result<BlockId> {
    if (!raw || raw.trim().length === 0) {
      return Result.fail<BlockId>('Block id cannot be empty.');
    }
    return Result.ok(new BlockId(raw.trim()));
  }

  /**
   * Generates a temporary, client-side identifier for a block that has not
   * been persisted yet. Prefixed with `tmp_` so the infrastructure layer
   * can distinguish new blocks from existing ones when syncing.
   *
   * @returns A new {@link BlockId} with a generated value.
   */
  public static generate(): BlockId {
    const random = Math.random().toString(36).slice(2, 10);
    return new BlockId(`tmp_${Date.now().toString(36)}_${random}`);
  }

  /**
   * Whether this id refers to a block that has not been persisted yet.
   *
   * @returns `true` when the id is a temporary client-side id.
   */
  public isTemporary(): boolean {
    return this.value.startsWith('tmp_');
  }

  /**
   * Structural equality on the wrapped string.
   *
   * @param other - The id to compare against.
   * @returns `true` when both wrap the same value.
   */
  public equals(other?: BlockId): boolean {
    return !!other && other.value === this.value;
  }
}
